# -*- coding: utf-8 -*-
"""Tes Sales Prediksi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17U1P8Tp8cgpMamW7zCZ-MStCAcGByntM
"""


import streamlit as st
import pandas as pd
from prophet import Prophet
from prophet.plot import plot_plotly
import plotly.graph_objs as go
from io import StringIO

st.set_page_config(page_title="Prediksi Penjualan", layout="centered")

st.title("📈 Prediksi Penjualan Produk")
st.write("Upload file CSV dengan dua kolom: `Tanggal` dan `Penjualan`.")

# Upload file
uploaded_file = st.file_uploader("Upload file CSV", type=["csv"])

if uploaded_file:
    # Baca data
    df = pd.read_csv('sales_data.csv')

    try:
        df['Tanggal'] = pd.to_datetime(df['Tanggal'])
        df = df.rename(columns={"Tanggal": "ds", "Penjualan": "y"})

        st.subheader("📊 Data yang Diupload")
        st.dataframe(df.())

        # Buat model Prophet
        model = Prophet()
        model.fit(df)

        # Prediksi untuk 30 hari ke depan
        future = model.make_future_dataframe(periods=30)
        forecast = model.predict(future)

        st.subheader("🔮 Hasil Prediksi Penjualan")
        fig = plot_plotly(model, forecast)
        st.plotly_chart(fig)

        # Tampilkan tabel prediksi
        st.subheader("📋 Tabel Prediksi")
        st.dataframe(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(30))

    except Exception as e:
        st.error(f"Terjadi kesalahan saat memproses data: {e}")

else:
    st.info("Silakan upload file CSV terlebih dahulu.")
